# Generated by Django 4.0 on 2022-01-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='massage',
            new_name='message',
        ),
    ]
